"""empty message

Revision ID: 14b368bbd883
Revises: 
Create Date: 2017-09-16 20:37:02.243737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b368bbd883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_info', sa.Column('ftp_urls', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_info', 'ftp_urls')
    # ### end Alembic commands ###
