"""empty message

Revision ID: 4d534d84dec1
Revises: f8a826866a14
Create Date: 2017-09-15 14:14:03.622783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d534d84dec1'
down_revision = 'f8a826866a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dyzz', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dyzz', sa.Column('time', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
