"""empty message

Revision ID: 716974e07825
Revises: 8d9a6d0b8511
Create Date: 2017-09-16 10:24:45.502241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716974e07825'
down_revision = '8d9a6d0b8511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie_info',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('thunder_urls', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Movie_info')
    # ### end Alembic commands ###
