"""empty message

Revision ID: 8d9a6d0b8511
Revises: 
Create Date: 2017-09-16 10:24:05.402006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d9a6d0b8511'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie_info',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('thunder_urls', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('movie_info')
    op.add_column('dyzz', sa.Column('error', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dyzz', 'error')
    op.create_table('movie_info',
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('thunder_urls', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Movie_info')
    # ### end Alembic commands ###
