"""initial migration

Revision ID: f8a826866a14
Revises: 
Create Date: 2017-09-15 14:13:11.072283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a826866a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dyzz', sa.Column('time', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dyzz', 'time')
    # ### end Alembic commands ###
